nyc_parking_violations_2:
  outputs:
    dev:
      type: duckdb
      path: '../data/nyc_parking_violations_2.db'
    prod:
      type: duckdb
      path: '../data/prod_nyc_parking_violations_2.db'
  target: dev